### PR TITLE
[duktape] Enable CPP exceptions

### PR DESCRIPTION
**Pull request by IntelOrca**

### CODE REVIEW

**Review by tupaschoal — APPROVED** [review]
Does that conflict with a changeset you did recently that you stopped using C++ exceptions?

**Comment by IntelOrca** [comment]
duktape uses setjmp for its exception handling even when we want to raise our own JS exceptions in native methods. This is very unsafe to do in C++ code with RAII and I think it is why we are getting fatal crashes in the plugin code. I am hoping this resolves that, but it will only be for Windows (and macOS I guess). Linux will be a big problem with it so centralised on using shared libraries. Duktape is designed to be compiled to specification, not used as a shared library.

**Comment by tupaschoal** [comment]
I see. Well you can go ahead and merge it, I guess.

**Comment by IntelOrca** [comment]
@tupaschoal I need to actually try using the new .lib first and see how well it works.

**Pull request closed without merging**
