### PR TITLE
Update the Dependencies and Add macOS Build

### PR DESCRIPTION
**Pull request by LRFLEW**
You probably shouldn't merge this yet. You can if the build succeeded, and someone tests it to make sure I didn't mess something up. However, **please** don't push a release for it yet. I have two more goals I want to hit (in this PR, or split up) before pushing it.

* Remove the private headers from the VS distribution
* Add a macOS build script to automate the build process

I'm mostly pushing this now so that I can get the CI to try building it and see where it possibly fails.

EDIT: It appears that freetype's Git server is having issues. I will look into an alternative if things don't fix themselves over there.

### CODE REVIEW

**Comment by IntelOrca** [comment]
I think we should start using submodules for everything rather than updating it with a new version.

**Comment by LRFLEW** [comment]
If we can find git versions of everything. The main problem with that is the series of patches that have to be applied to the VS projects, but I think we can make it work.

**Comment by janisozaur** [comment]
@LRFLEW it's `lodepng`, as in `Lode Vandevenne`, not `loadpng`, nor `Load Vandevenne`. Please do not mangle names.

**Comment by IntelOrca** [comment]
@LRFLEW yeah, you can see I already do that with SDL2 - because they don't provide static configurations. For things like libpng and zlib, you can use some random GitHub mirror.

**Comment by LRFLEW** [comment]
@janisozaur Sorry about that. I fixed the commit message. I've always thought it was loadpng, but then again, this is the only place I've ever seen it.

@IntelOrca Ok, I'll work on finding (and replacing with) suitable submodules tomorrow. There will be a few files I'll want to keep in the repository (namely the jansson config files and libspeexdsp (that is, unless you want to build the entire library for the project like I have done previously for the macOS builds)). I'll still try to get this building first to look for any problems before redoing everything.

**Comment by IntelOrca** [comment]
@LRFLEW jansson supports an msbuild config for cmake which you can see being used on their AppVeyor builds. We could use that if allows us to configure it correctly.

**Comment by janisozaur** [comment]
OpenSSL is outdated as well

**Comment by LRFLEW** [comment]
@janisozaur Thanks for pointing that out. I don't follow the OpenSSL updates that closely, so I didn't see that. It's a simple variable in the build script from what I've seen, so it shouldn't be too hard to update.

I'm also sure that breakpad is on an older version, but I'm not sure what's up with the release system for that. @janisozaur is the one that added it to the repository from what I've seen, so any insight from you would help. From what I can see, breakpad is distributed via git, so adding it as a submodule shouldn't be too difficult. I just want to use a stable release, and I'm not sure how that's organized.

One note about OpenSSL: there's now a new semi-API-incompatible release of OpenSSL with the 1.1.0 branch. The 1.0.2 is still supported, and will be for a long time as a LTS branch, so it wouldn't be bad to stick with that branch and just update to the latest revision. However, with one of the changes here, we will no longer be using OpenSSL for libcurl, so the only API-compatibility we need to worry about is our usage, and since we aren't using it's SSL/TLS session code, it's less of an issue if we are using a fresher version. @janisozaur Do you know if OpenRCT2 works with OpenSSL/libcrypto 1.1.0 on Linux? That should be a good indicator for Windows/macOS.

**Comment by LRFLEW** [comment]
From what I can tell from my testing, OpenSSL/libcrypto 1.1.0b works with OpenRCT2. I'll probably stick with 1.0.2, though, as the LTS makes more sense to me right now. (Even brew on macOS has the `openssl` formula at 1.0.2, and uses a separate `openssl@1.1` for 1.1.0).

**Comment by janisozaur** [comment]
I have not tested with OpenSSL 1.1.0, Arch certainly has not updated to this branch yet, it's only available in Fedora rawhide (what's to become F25 in near future).

I'm happy to have OpenRCT2 stay on LTS version. If there are any changes required, can you push them to main repo?

**Comment by LRFLEW** [comment]
Just tested the AppVeyor build in Visual Studio. It does build, and seems to work correctly. I was able to pull the server list (which uses libcurl's SSL capabilities) and join a server (which uses OpenSSL's RSA library), and the rest was largely passively tested (SDL2 created a window, etc.).

I did need to add two libraries to Visual Studio's linking settings to get the Schannel-dependent libcurl build to work. These libraries were Crypto32.lib and Wldap32.lib (both use the same names for x86 and x64 builds). This will need to be updated when the libs get updated.

**Comment by LRFLEW** [comment]
Ok, I've updated everything to use submodules, except breakpad. It appears like that would be fairly straight forward, but I don't understand how to get it, or how to ask for a "stable" version. @janisozaur If you have the chance, could you look into this? Github says you were the one to add it originally, so you should know more than me about this.

**Comment by janisozaur** [comment]
I'll try, but it may take some time. If you can push it with current breakpad, that's fine by me.

**Comment by LRFLEW** [comment]
Ok, **now** everything should be updated correctly. I had to fix a few build issues, and I forgot to make a handful of changes I meant to. However, the original purpose for this PR should be done.

I have added another commit, this time adding a Travis build to make the macOS dependencies. The script I wrote can build 32-bit libraries, but since the plan is to ditch With-RCT2 builds, I'm not having the Travis build use that. Once it's merged, someone with permissions to create oauth keys for the repository should add the release deployment to the Travis config.

For an example of the Travis build, [here's a build log](https://travis-ci.org/LRFLEW/Dependencies/builds/168000508), and [here's the resulting zip](https://transfer.sh/toviW/openrct2-libs-macos.zip).

**Comment by LRFLEW** [comment]
Never mind, gave up on the header thing. It's not as bad as it was previously, with zlib and libpng being the main offenders at this point. @IntelOrca's branch where he converts the powershell scripts to Visual Studio projects would be the better place to make that fix. Therefore, I'm going to go ahead and remove the [WIP] tag from the PR.

**Pull request merged**
