### PR TITLE
bundle debug and release deps

### PR DESCRIPTION
**Pull request by tobiaskohlbau**
It's not possible to build OpenRCT2 with debug runtime without static dependencies also provided as debug. VCPKG builds them anyway so it's not a big deal to bundle them in.

### CODE REVIEW

**Comment by IntelOrca** [comment]
Currently AppVeyor times out (1 hour) due to how long it takes to build the libraries.

**Comment by janisozaur** [comment]
See https://github.com/Microsoft/vcpkg/issues/2368

**Comment by tobiaskohlbau** [comment]
I hoped that cashing would help if it gets cached on error but unfortunately that doesn't worked out. I could provide a local artifact if you want to save some time for compiling by yourself.

**Comment by IntelOrca** [comment]
Our next version of dependencies needs the latest discord-rpc. The cURL vcpkg package also needs manually amending to have Windows certificate support enabled.

**Comment by tobiaskohlbau** [comment]
Is the current version patched for windows certificates. What's the reason for need of the latest discord-rpc?

**Comment by janisozaur** [comment]
> What's the reason for need of the latest discord-rpc?

https://github.com/OpenRCT2/OpenRCT2/issues/6741 and https://github.com/discordapp/discord-rpc/pull/68

**Comment by IntelOrca** [comment]
@tobiaskohlbau I did it manually when I manually built the dependencies.

More info: https://github.com/Microsoft/vcpkg/issues/1910

For discord I think it was to add Windows Vista compatibility.

**Comment by tobiaskohlbau** [comment]
I got it, I thought you wanna change this before the release of next deps package. Build it's build different right now. 

Would you like to update it or should I modify my local version and send you the bundled package?

**Comment by IntelOrca** [comment]
https://github.com/Microsoft/vcpkg/tree/master/ports/discord-rpc

This needs updating first.

**Comment by janisozaur** [comment]
I also need to update vcpkg recipe for libzip

**Comment by tobiaskohlbau** [comment]
I've updated libzip and discord-rpc and added an option for building curl with winssl. Let's wait for upstream merging.

**Comment by janisozaur** [comment]
discord-rpc: https://github.com/Microsoft/vcpkg/pull/2632 (already merged)
libzip: https://github.com/Microsoft/vcpkg/pull/2633 (needs to account for changes upstream that address https://github.com/OpenRCT2/OpenRCT2/issues/6682)
curl+winssl: https://github.com/Microsoft/vcpkg/pull/2631 (awaiting merge)

**Comment by tobiaskohlbau** [comment]
It's all merged now :-)

**Comment by IntelOrca** [comment]
@tobiaskohlbau Why have you moved the commands from install.bat to the appveyor yml? This stops other build machines (necessary as AppVeyor times out) from building the dependencies.

**Comment by tobiaskohlbau** [comment]
I've removed them only cause I'm disliking running external scripts within CI. But it's worth separating it as you sayed AppVeyor times out...

**Comment by IntelOrca** [comment]
What changes do I need to make to the script to make curl build with Windows CA support?

**Comment by tobiaskohlbau** [comment]
See https://github.com/Microsoft/vcpkg/pull/2631 for information.

**Comment by IntelOrca** [comment]
@tobiaskohlbau I saw that, could you provide an example of how to do that in the context of this repository?

**Comment by janisozaur** [comment]
@IntelOrca I think you're supposed to copy one of exiting triplets, e.g. https://github.com/Microsoft/vcpkg/blob/master/triplets/x86-windows.cmake and add the relevant option there.

**Comment by tobiaskohlbau** [comment]
@IntelOrca as told by maintainer it's your decision if you modify target triplet or use a new one (https://github.com/ras0219-msft).

> Yes, you'd add it to your local triplet (which could be x64-windows or x64-windows-tobiaskohlbau -- whichever works best for you).

**Comment by janisozaur** [comment]
There's now breakpad entry in vcpkg: https://github.com/Microsoft/vcpkg/commit/0f607865f36fa8988288ca666395d52b32762ac7

**Comment by janisozaur** [comment]
This should be superseded by #18

**Pull request closed without merging**
