### PR TITLE
Add gtest to macos libraries

### PR DESCRIPTION
**Pull request by janisozaur**

### CODE REVIEW

**Comment by janisozaur** [comment]
hey @adam-bloom can you please take a look? This is to address https://github.com/OpenRCT2/OpenRCT2/pull/15914

**Review by adam-bloom — APPROVED** [review]
I was hoping to download the test artifact to take a peek, but something is up with my internet connection and my GitHub downloads keep failing.

The only concern I have is one we’d address in the linked PR. Right now, all libraries from this artifact are copied into the macOS app bundle. Depending on how large gtest is, it may be worth adding some logic to modify that behavior a bit. If it’s small, probably not worth making any changes. (And I can’t see the final size without that download!)

**Comment by adam-bloom** [comment]
I was able to download today - looks like it'll add 1-2 MB to the OpenRCT2 app bundle. That's probably small enough that we can just ignore it, rather than adding packaging code to handle this case.

**Comment by tupaschoal** [comment]
Good to go, then @janisozaur ?

**Comment by janisozaur** [comment]
Yes, but needs to be done according to the process in readme - currently there is no tag in the pr

**Pull request merged**
