### PR TITLE
Use macos-14 workers to create libraries

### PR DESCRIPTION
**Pull request by janisozaur**
The macos-14 is already arm-based image

### CODE REVIEW

**Comment by janisozaur** [comment]
cc @pdewit @AaronVanGeffen

**Comment by janisozaur** [comment]
https://github.com/microsoft/vcpkg/issues/39736

**Comment by AaronVanGeffen** [comment]
Can we work around the vcpkg libpng issue, somehow? Does it present itself if we do not update the pinned vcpkg commit hash, for example?

**Comment by janisozaur** [comment]
It's still present in older vcpkg. I'll look into that

**Comment by janisozaur** [comment]
Note: this only happens in our custom triplet. Using arm64 host to build amd64 package with vcpkg's own triplet works ok.

**Comment by duncanspumpkin** [comment]
> Note: this only happens in our custom triplet. Using arm64 host to build amd64 package with vcpkg's own triplet works ok.

what is special about our triplet?

**Comment by janisozaur** [comment]
We link statically, vcpkg prefers dynamic linking

**Comment by AaronVanGeffen** [comment]
So it was a one-line fix in the triplet, in the end? Nice work!

**Comment by janisozaur** [comment]
Yeah, it was just that line missing. Once this is approved & merged, I still need to push a tag for new release.

**Review by AaronVanGeffen — APPROVED** [review]
Changes look good to me. Haven't tested the resulting dep bundle, but that can be done once it is hooked up to the OpenRCT2 CI. Could you amend https://github.com/OpenRCT2/OpenRCT2/pull/22601 to that end?

**Pull request merged**
