### PR TITLE
GitHub actions (with macOS)

### PR DESCRIPTION
**Pull request by adam-bloom**
Extends the work started by @janisozaur to add macOS to GitHub actions and remove all old build scripts.

Questions before merging:

- @janisozaur set up GitHub actions to create draft releases for each GitHub CI run, including PRs. Draft releases are private, so they do not clutter the public view. I'm not sure they're really needed for PRs, since a release is likely only going to be made from master. Thoughts on whether to keep them? They do make testing of changes easy, since you can point your OpenRCT2 branch at a release for your fork, but they also have the potential to introduce lots of draft releases on repos.
- @IntelOrca is your duktape patch still needed? Since the windows builds now pull directly from vcpkg, I don't think it is used.
- Someone with admin access on this repo will need to remove the AppVeyor check - it still tries to run on each PR commit.
- @LRFLEW do you think we should pin the commit of vcpkg used for macOS builds? @janisozaur pinned the commit for windows builds (which I updated to get things working again). Do we want to pin to the same commit as windows or should both releases be allowed to pin separately?

If anyone wants to preview the actions output or review the built artifacts, they're available on my fork: https://github.com/adam-bloom/Dependencies/actions

### CODE REVIEW

**Comment by LRFLEW** [comment]
>@LRFLEW do you think we should pin the commit of vcpkg used for macOS builds? @janisozaur pinned the commit for windows builds (which I updated to get things working again). Do we want to pin to the same commit as windows or should both releases be allowed to pin separately?

If it's being pinned for Windows, then I guess it should be pinned for macOS as well. As to whether Windows and macOS should use the same pinning... probably? I'm sure there could be a situation where they might want to be kept separate, but also worry that allowing that will cause the macOS dependency updates to be neglected due to the lack of people focused on it. So... just do whatever makes the most sense.

**Comment by IntelOrca** [comment]
> @janisozaur set up GitHub actions to create draft releases for each GitHub CI run, including PRs.
I doubt this was intentional or only used to test it. Releases should only be created on tagged commits.

> @IntelOrca is your duktape patch still needed? Since the windows builds now pull directly from vcpkg, I don't think it is used.
We plan to include duktape in OpenRCT2 sources as it has to be heavily configured using build macros. So we will probably remove duktape altogether soon from the dependencies. You can ignore that PR.

> Someone with admin access on this repo will need to remove the AppVeyor check - it still tries to run on each PR commit.
I will remove it when GitHub actions is up and running.

**Comment by adam-bloom** [comment]
Thanks for the feedback. macOS and Windows are now pinned to the same vcpkg commit (which I've gone ahead and set to the current vcpkg master latest commit).

@IntelOrca for release creation, I've added a workflow that runs when a tagged v* commit is pushed (i.e. v28) and automatically creates the corresponding release and creates/attaches the dependency zip files. See https://github.com/adam-bloom/Dependencies/releases/tag/v123 and https://github.com/adam-bloom/Dependencies/actions/runs/526190580. The regular CI run is suppressed for tag pushes.

Is the current workflow to create a release via CLI and push or via the Github web UI? The latter currently triggers the "Create release" job, but it does not work for that use case, as it tries to create a duplicate release. I'd need to add a bit of logic to check if the release already exists (and if so, just create and upload the artifacts). Let me know if that's the right workflow, or if we should just add a note to the readme about using the GitHub CLI to create a tag and let the actions workflow create the release.

Note that the macOS builds do not cache right now, so they'll take ~15 minutes to rebuild after a tag/release, even if its the same commit that already passed CI. I think this is ok - releases are not made very often right now, so the amount of time saved is likely much less than the time required to test caching.

**Comment by IntelOrca** [comment]
Is there any reason to have two workflows? I would have thought creating a release would be a job that runs after the normal build but only if it is a tagged commit.

**Comment by IntelOrca** [comment]
@adam-bloom I was able to get releases working without using a separate CI file. See my example here:
https://github.com/OpenRCT2/title-sequence-editor/blob/main/.github/workflows/ci.yml

**Comment by adam-bloom** [comment]
> @adam-bloom I was able to get releases working without using a separate CI file. See my example here:
> https://github.com/OpenRCT2/title-sequence-editor/blob/main/.github/workflows/ci.yml

I hadn't had time to play around myself - glad you did! I figured there had to be a way too. I'll try to get a revision done this weekend.

**Comment by adam-bloom** [comment]
@IntelOrca I think this is good to go now.
PR CI run (not v* tagged): https://github.com/adam-bloom/Dependencies/actions/runs/606871052
Release creation (v123): https://github.com/adam-bloom/Dependencies/actions/runs/606871338

**Comment by IntelOrca** [comment]
@adam-bloom thanks, let's merge it now and see what happens.

**Comment by adam-bloom** [comment]
@IntelOrca can you also tag that commit on master as the next release version? That should generate the release after that.

**Pull request merged**
